export const darkTheme = {
  mode: 'dark',
  PRIMARY_BACKGROUND_COLOR: '#121212',
  SECONDARY_BACKGROUND_COLOR: '#1E1E1E',
  PRIMARY_TEXT_COLOR: '#fff',
  SECONDARY_TEXT_COLOR: '#ccc',
  PRIMARY_BUTTON_COLOR: '#1E1E1E',
  SECONDARY_BUTTON_COLOR: '#121212',
  PRIMARY_BUTTON_TEXT_COLOR: '#fff',
  SECONDARY_BUTTON_TEXT_COLOR: '#ccc',
  STATUS_BAR_STYLE: 'light-content',
};

export const lightTheme = {
  mode: 'light',
  PRIMARY_BACKGROUND_COLOR: '#fff',
  SECONDARY_BACKGROUND_COLOR: '#F2F2F2',
  PRIMARY_TEXT_COLOR: '#121212',
  SECONDARY_TEXT_COLOR: '#666',
  PRIMARY_BUTTON_COLOR: '#1E1E1E',
  SECONDARY_BUTTON_COLOR: '#121212',
  PRIMARY_BUTTON_TEXT_COLOR: '#fff',
  SECONDARY_BUTTON_TEXT_COLOR: '#ccc',
  STATUS_BAR_STYLE: 'dark-content',
};
